import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'package:shared_preferences/shared_preferences.dart';

const ownerUsername = 'Siavashmorad';
const apiBase = 'https://api1.tabdeal.org';

void main() => runApp(const SignalApp());

class SignalApp extends StatefulWidget { const SignalApp({super.key}); @override State<SignalApp> createState()=>_SignalAppState(); }
class _SignalAppState extends State<SignalApp> {
  bool dark=false, english=false, logged=false;
  @override void initState(){super.initState(); _load();}
  Future<void> _load() async { final p=await SharedPreferences.getInstance(); setState(()=>logged=p.getBool('logged')??false); }
  @override Widget build(BuildContext context)=>MaterialApp(debugShowCheckedModeBanner:false, themeMode:dark?ThemeMode.dark:ThemeMode.light, theme:_theme(false), darkTheme:_theme(true), home:logged?HomePage(english:english,dark:dark,onLang:()=>setState(()=>english=!english),onTheme:()=>setState(()=>dark=!dark),onLogout:()async{final p=await SharedPreferences.getInstance();await p.setBool('logged',false);setState(()=>logged=false);}):LoginPage(english:english,onLogin:()=>setState(()=>logged=true)));
  ThemeData _theme(bool d)=>ThemeData(useMaterial3:true,brightness:d?Brightness.dark:Brightness.light,colorSchemeSeed:const Color(0xFF5B4BDB),fontFamily:'sans-serif');
}

class LoginPage extends StatefulWidget { final bool english; final VoidCallback onLogin; const LoginPage({super.key,required this.english,required this.onLogin}); @override State<LoginPage> createState()=>_LoginPageState(); }
class _LoginPageState extends State<LoginPage>{ final u=TextEditingController(text:ownerUsername),p=TextEditingController(); String? error;
 Future<void> login()async{ if(u.text.trim()!=ownerUsername||p.text.length<6){setState(()=>error=widget.english?'Username or password is invalid.':'نام کاربری یا رمز عبور صحیح نیست.');return;} final pref=await SharedPreferences.getInstance();await pref.setBool('logged',true);widget.onLogin(); }
 @override Widget build(BuildContext c)=>Scaffold(body:Center(child:SingleChildScrollView(padding:const EdgeInsets.all(28),child:ConstrainedBox(constraints:const BoxConstraints(maxWidth:430),child:Card(child:Padding(padding:const EdgeInsets.all(26),child:Column(children:[const CircleAvatar(radius:38,child:Icon(Icons.candlestick_chart,size:38)),const SizedBox(height:18),Text('Signal Scanner',style:Theme.of(c).textTheme.headlineSmall?.copyWith(fontWeight:FontWeight.bold)),const SizedBox(height:6),Text(widget.english?'Private access':'ورود خصوصی و اختصاصی',textAlign:TextAlign.center),const SizedBox(height:26),TextField(controller:u,decoration:InputDecoration(labelText:widget.english?'Username':'نام کاربری',prefixIcon:const Icon(Icons.person))),const SizedBox(height:14),TextField(controller:p,obscureText:true,decoration:InputDecoration(labelText:widget.english?'Password':'رمز عبور',prefixIcon:const Icon(Icons.lock))),if(error!=null)Padding(padding:const EdgeInsets.only(top:12),child:Text(error!,style:TextStyle(color:Theme.of(c).colorScheme.error))),const SizedBox(height:22),SizedBox(width:double.infinity,height:52,child:FilledButton.icon(onPressed:login,icon:const Icon(Icons.login),label:Text(widget.english?'Sign in':'ورود'))),const SizedBox(height:12),Text(widget.english?'Only the owner account is accepted.':'فقط حساب مالک برنامه پذیرفته می‌شود.',style:Theme.of(c).textTheme.bodySmall)])))))); }
}

class Signal { final String symbol,side,timeframe; final double score,entry,stop,tp; Signal(this.symbol,this.side,this.timeframe,this.score,this.entry,this.stop,this.tp); }

class HomePage extends StatefulWidget { final bool english,dark; final VoidCallback onLang,onTheme,onLogout; const HomePage({super.key,required this.english,required this.dark,required this.onLang,required this.onTheme,required this.onLogout}); @override State<HomePage> createState()=>_HomePageState(); }
class _HomePageState extends State<HomePage>{ bool loading=false; String timeframe='15m'; double capital=10000000; Signal? signal; String? status;
 final symbols=['BTCUSDT','ETHUSDT','SOLUSDT','XRPUSDT','DOGEUSDT','ADAUSDT','SUIUSDT','PEPEUSDT'];
 Future<List<dynamic>> getJson(String path,Map<String,String> q)async{final uri=Uri.parse('$apiBase$path').replace(queryParameters:q);final r=await http.get(uri).timeout(const Duration(seconds:8));if(r.statusCode!=200)throw Exception('HTTP ${r.statusCode}');return jsonDecode(r.body) as List<dynamic>;}
 Future<Map<String,dynamic>> depth(String s)async{final uri=Uri.parse('$apiBase/r/api/v1/depth').replace(queryParameters:{'symbol':s,'limit':'30'});final r=await http.get(uri).timeout(const Duration(seconds:8));if(r.statusCode!=200)throw Exception();return jsonDecode(r.body);}
 Future<void> scan()async{setState(()=>{loading=true,status=null,signal=null}); final found=<Signal>[]; for(final s in symbols){try{final t=await getJson('/r/api/v1/trades',{'symbol':s,'limit':'300'});if(t.length<30)continue;final prices=t.map((e)=>double.tryParse('${e is List?e[0]:e['price']}')??0).where((x)=>x>0).toList();if(prices.length<30)continue;final entry=prices.last, old=prices[prices.length~/3], change=(entry-old)/old*100;final d=await depth(s);double bid=0,ask=0;for(final x in (d['bids']??[]))bid+=double.parse('${x[1]}');for(final x in (d['asks']??[]))ask+=double.parse('${x[1]}');final imbalance=(bid+ask)==0?0:(bid-ask)/(bid+ask);final side=change>=0&&imbalance>=-0.15?'LONG':'SHORT';final score=(50+change.abs().clamp(0,20)*2+imbalance*25).clamp(0,100).toDouble();final risk=entry*0.006;final stop=side=='LONG'?entry-risk:entry+risk;final tp=side=='LONG'?entry+risk*2.5:entry-risk*2.5;if(score>=62)found.add(Signal(s,side,timeframe,score,entry,stop,tp));}catch(_){}}
 found.sort((a,b)=>b.score.compareTo(a.score));setState(()=>{loading=false;signal=found.isEmpty?null:found.first;status=found.isEmpty?(widget.english?'No valid setup found.':'سیگنال معتبر پیدا نشد.'):(widget.english?'Scan completed.':'اسکن بازار انجام شد.');}); }
 String n(double x)=>x.toStringAsFixed(x>=1000?2:6);
 @override Widget build(BuildContext c){final en=widget.english;return Scaffold(appBar:AppBar(title:Text(en?'Signal Scanner':'اسکنر سیگنال'),actions:[IconButton(onPressed:widget.onTheme,icon:Icon(widget.dark?Icons.light_mode:Icons.dark_mode)),IconButton(onPressed:widget.onLang,icon:const Icon(Icons.language)),IconButton(onPressed:widget.onLogout,icon:const Icon(Icons.logout))]),body:RefreshIndicator(onRefresh:scan,child:ListView(padding:const EdgeInsets.all(16),children:[Card(child:Padding(padding:const EdgeInsets.all(18),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(en?'Market scanner':'اسکن بازار',style:Theme.of(c).textTheme.titleLarge?.copyWith(fontWeight:FontWeight.bold)),const SizedBox(height:12),Row(children:[Expanded(child:DropdownButtonFormField<String>(value:timeframe,decoration:InputDecoration(labelText:en?'Timeframe':'تایم‌فریم'),items:['1m','5m','15m','1h'].map((x)=>DropdownMenuItem(value:x,child:Text(x))).toList(),onChanged:(v)=>setState(()=>timeframe=v!))),const SizedBox(width:12),Expanded(child:TextFormField(initialValue:'10000000',keyboardType:TextInputType.number,decoration:InputDecoration(labelText:en?'Capital (Toman)':'سرمایه (تومان)'),onChanged:(v)=>capital=double.tryParse(v.replaceAll(',',''))??capital))]),const SizedBox(height:16),SizedBox(width:double.infinity,height:52,child:FilledButton.icon(onPressed:loading?null:scan,icon:loading?const SizedBox(width:20,height:20,child:CircularProgressIndicator(strokeWidth:2)):const Icon(Icons.radar),label:Text(loading?(en?'Scanning...':'در حال اسکن...'):(en?'Scan best opportunity':'پیدا کردن بهترین فرصت'))))])),const SizedBox(height:14),if(status!=null&&!loading)Card(child:ListTile(leading:Icon(signal==null?Icons.block:Icons.check_circle),title:Text(status!))),if(signal!=null)_SignalCard(signal:signal!,en:en),const SizedBox(height:10),Card(child:const ListTile(leading:Icon(Icons.shield_outlined),title:Text('Signal-only mode'),subtitle:Text('No orders are sent to the exchange.')))])));
}
}
class _SignalCard extends StatelessWidget{final Signal signal;final bool en;const _SignalCard({required this.signal,required this.en});String n(double x)=>x.toStringAsFixed(6);@override Widget build(BuildContext c)=>Card(child:Padding(padding:const EdgeInsets.all(20),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[Text(signal.symbol,style:Theme.of(c).textTheme.headlineSmall?.copyWith(fontWeight:FontWeight.bold)),Chip(label:Text(signal.side))]),Text('${en?'Timeframe':'تایم‌فریم'}: ${signal.timeframe}'),const Divider(height:28),_r(c,en?'Signal score':'امتیاز سیگنال','${signal.score.toStringAsFixed(0)}/100'),_r(c,en?'Entry':'نقطه ورود',n(signal.entry)),_r(c,en?'Stop Loss':'حد ضرر',n(signal.stop)),_r(c,en?'Take Profit':'حد سود',n(signal.tp)),_r(c,en?'Risk/Reward':'ریسک به سود','1 : 2.5')])));Widget _r(BuildContext c,String a,String b)=>Padding(padding:const EdgeInsets.symmetric(vertical:6),child:Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[Text(a),Text(b,style:const TextStyle(fontWeight:FontWeight.bold))]));}
